type: default
time: 3000ms
memory: 512m
filename: tree
checker_type: default

subtasks:
  - score: 4
    type: min
    cases:
      - input:  tree_sub01_pt01.in
        output: tree_sub01_pt01.ans
      - input:  tree_sub01_pt02.in
        output: tree_sub01_pt02.ans
      - input:  tree_sub01_pt03.in
        output: tree_sub01_pt03.ans
  - score: 12
    type: min
    cases:
      - input:  tree_sub02_pt01.in
        output: tree_sub02_pt01.ans
      - input:  tree_sub02_pt02.in
        output: tree_sub02_pt02.ans
      - input:  tree_sub02_pt03.in
        output: tree_sub02_pt03.ans
      - input:  tree_sub02_pt04.in
        output: tree_sub02_pt04.ans
      - input:  tree_sub02_pt05.in
        output: tree_sub02_pt05.ans
      - input:  tree_sub02_pt06.in
        output: tree_sub02_pt06.ans
  - score: 36
    type: sum
    cases:
      - input:  tree_sub03_pt01.in
        output: tree_sub03_pt01.ans
      - input:  tree_sub03_pt02.in
        output: tree_sub03_pt02.ans
      - input:  tree_sub03_pt03.in
        output: tree_sub03_pt03.ans
      - input:  tree_sub03_pt04.in
        output: tree_sub03_pt04.ans
      - input:  tree_sub03_pt05.in
        output: tree_sub03_pt05.ans
      - input:  tree_sub03_pt06.in
        output: tree_sub03_pt06.ans
  - score: 12
    type: sum
    cases:
      - input:  tree_sub04_pt01.in
        output: tree_sub04_pt01.ans
      - input:  tree_sub04_pt02.in
        output: tree_sub04_pt02.ans
      - input:  tree_sub04_pt03.in
        output: tree_sub04_pt03.ans
      - input:  tree_sub04_pt04.in
        output: tree_sub04_pt04.ans
      - input:  tree_sub04_pt05.in
        output: tree_sub04_pt05.ans
      - input:  tree_sub04_pt06.in
        output: tree_sub04_pt06.ans
  - score: 36
    type: sum
    cases:
      - input:  tree_sub05_pt01.in
        output: tree_sub05_pt01.ans
      - input:  tree_sub05_pt02.in
        output: tree_sub05_pt02.ans
      - input:  tree_sub05_pt03.in
        output: tree_sub05_pt03.ans
      - input:  tree_sub05_pt04.in
        output: tree_sub05_pt04.ans
      - input:  tree_sub05_pt05.in
        output: tree_sub05_pt05.ans
      - input:  tree_sub05_pt06.in
        output: tree_sub05_pt06.ans
