type: default
time: 5s
memory: 512m
filename: library
checker_type: default

subtasks:
  - score: 100
    type: sum
    cases:
      - input:  library_sub01_pt01.in
        output: library_sub01_pt01.ans
      - input:  library_sub01_pt02.in
        output: library_sub01_pt02.ans
      - input:  library_sub01_pt03.in
        output: library_sub01_pt03.ans
      - input:  library_sub01_pt04.in
        output: library_sub01_pt04.ans
      - input:  library_sub01_pt05.in
        output: library_sub01_pt05.ans
      - input:  library_sub01_pt06.in
        output: library_sub01_pt06.ans
      - input:  library_sub01_pt07.in
        output: library_sub01_pt07.ans
      - input:  library_sub01_pt08.in
        output: library_sub01_pt08.ans
      - input:  library_sub01_pt09.in
        output: library_sub01_pt09.ans
